# Site settings
title: Richard Polzin
description: Richard Polzin's Personal Website
favicon: /assets/img/avatar.JPG
baseurl: http://iaidoaachen.de/personal-website
url: http://iaidoaachen.de/personal-website
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Richard Polzin
  title: Artificial Intelligence Master Student
  address: Aachen, Germany
  email: polzin.richard@gmail.com
  link: http://richardpolzin.com
  weibo:
  github: DeastinY
  linkedin: richard-polzin
  twitter:
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Maastricht University
      location: Maastricht, Netherlands
      title: Master Student
      started: 2016
      duration: (2016 - Present)
      description: 
    - work2:
      company: Fachhochschule Aachen / ModuleWorks GmbH
      location: Aachen, Germany
      title: Bachelor Student / Trainee
      started: 2013
      duration: (2013 - 2016)
      description: 
  educationHistory:
    - education1:
      organization: Fachhochschule Aachen
      location: Aachen, Germany
      degree: Bachelor of Science
      major:
      started: 20013
      duration: (2013 - 2016)
      description:
    - education2:
      organization: Berufsschule Alsdorf
      location: Alsdorf, Germany
      degree: Abitur
      major:
      started: 20010
      duration: (2010 - 2013)
      description: 
  languages:
    - language1:
      name: German
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Python
      percentage: 100%
    - skill2:
      name: C#
      percentage: 90%
    - skill3:
      name: Java
      percentage: 70%
  publications:
    - publication1:
      name: Localization for Robot Soccer
      author: A. Diener, F. Fuss, R. Polzin
      link: http://richardpolzin.com/publications/NAO_Localization.pdf
      date: 2017-01-25
