# Site settings
title: Richard Polzin
description: Richard Polzin's Personal Website
favicon: /assets/img/avatar.JPG
baseurl: http://iaidoaachen.de/personal-website
url: http://iaidoaachen.de/personal-website
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Richard Polzin
  title: Artificial Intelligence Master Student
  address: Aachen, Germany
  email: polzin.richard@gmail.com
  link: http://richardpolzin.com
  weibo:
  github: DeastinY
  linkedin: richard-polzin
  twitter:
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Maastricht University
      location: Maastricht, Netherlands
      title: Master Student
      started: 2016
      duration: (2016 - Present)
      description: I am currently expanding my knowledge in the fields of machine learning, game theory and robotics. The concepts of artificial intelligence are fascinating and their application is something that has attracted me for quite some time during the Bachelor.
    - work2:
      company: Fachhochschule Aachen / ModuleWorks GmbH
      location: Aachen, Germany
      title: Bachelor Student / Trainee
      started: 2013
      duration: (2013 - 2016)
      description: During the three years of apprenticeship and studies I learned a lot about the working life and got in contact with many great people.
  educationHistory:
    - education1:
      organization: Fachhochschule Aachen
      location: Aachen, Germany
      degree: Bachelor of Science
      major:
      started: 20013
      duration: (2013 - 2016)
      description:
    - education2:
      organization: Berufsschule Alsdorf
      location: Alsdorf, Germany
      degree: Abitur
      major:
      started: 20010
      duration: (2010 - 2013)
      description: As soon as I knew that I wanted to pursue an IT career I changed to a school that offered more specialized IT courses. This allowed to have several specialized IT courses already during high school. During this time I was able to learn about topics like programming, databases, networking or game development very early from great teachers.
  languages:
    - language1:
      name: German
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Python
      percentage: 100%
    - skill2:
      name: C#
      percentage: 90%
    - skill3:
      name: Java
      percentage: 70%
  publications:
    - publication1:
      name: Localization for Robot Soccer
      author: A. Diener, F. Fuss, R. Polzin
      link: https://github.com/DeastinY/personal-website/blob/gh-pages/publications/NAO_Localization.pdf
      date: 2017-01-25
